### ISSUE TITLE
Rewrite test_version

### ISSUE THREAD

**Issue by pmayd** [CorrelAid/pystatis#1]
Right now test_version is a dummy test that does more harm than it's helpful. I want to rewrite the test so it compares the version in __init__, that defines the pystatis.__version__ attribute, with the version stated in the pyproject.toml file. This would assure that we'll never ever forget to updated both again (should even be a pre commit hook)

**Comment by bergnerjonas** [comment]
Fixed in version 0.2.0 https://github.com/CorrelAid/pystatis/pull/50
