### ISSUE TITLE
Update Sphinx Documentation: Docstring Inheritance Fix and Auto-Deployment

### ISSUE THREAD

**Issue by MarcoHuebner** [CorrelAid/pystatis#10]
Our current Sphinx documentation seems to have incorrect docstring inheritance (not displayed at all), and we should streamline the deployment process by automatically publishing the documentation to e.g. GitHub Pages (for alternatives see [Sphinx guidelines](https://www.sphinx-doc.org/en/master/tutorial/deploying.html)).

Implementation Steps:

Docstring Inheritance:
- Verify that inherited docstrings accurately reflect the functionality of overridden methods and attributes and are compatible with Sphinx.

Auto-deployment to e.g. GitHub Pages:
- Search for accessible hosting platforms and open-source standards.
- Set up an automated process to build and deploy the Sphinx documentation.
- Ensure that the documentation build process is robust and can handle variations in the codebase.
- Consider versioning the documentation to maintain historical records of previous releases.

**Comment by MarcoHuebner** [comment]
TODOs:

1. Adjust the artifact storage time if necessary
2. Set up GitHub pages. **Steps:**

-Create a gh-pages branch (or any other name)
- Add an index.html (copy from build/html) and maybe .nojekyll or _config.yml (see [here](https://docs.github.com/en/pages/quickstart)) to the documentation publish (e.g. gh-pages) branch
- Decide whether to use [GitHub Token](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-first-deployment-with-github_token) or [deploy SSH Key](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-create-ssh-deploy-key) ->
- After that, the documentation should automatically be hosted at http://correlaid.github.io/pystatis

**Comment by pmayd** [comment]
I looked into the documentation and GitHub Tokens seams to be the easy way because no setup required, so ideal...but they also saying that it has some limitations and something is needed when run first but I did not really understand. I can take over the deployment SSH Key and set up everything as I think that is the more professional solution

**Comment by pmayd** [comment]
I have added the deploy SSH key to the repository, so you can use it now, see details in PR and your linked documentation

**Comment by MarcoHuebner** [comment]
Dev documentation is now hosted under https://correlaid.github.io/pystatis/dev/, main documentation (pending) under https://correlaid.github.io/pystatis/
