### ISSUE TITLE
Support changing the regional depth for a query

### ISSUE THREAD

**Issue by pmayd** [CorrelAid/pystatis#109]
Both in Regionalstatistik and Zensus we have the possibility in the UI to change the regional depth (Deutschland, Bundesländer, Kreise, Gemeinden etc.) for a given table and evas number. 

Can we support this in our library?

**Comment by bergnerjonas** [comment]
The specification of the regional depth is possible by speciying the query paramer `classifyingvariable1` in the get request to the respective code of the variable. E.g. for 12411-01-01-5-B:

- `classifyingvariable1=GEMEIN` -> use Gemeinde
- `classifyingvariable1=DLAND` -> use Bundesland

**Comment by pmayd** [comment]
Yeah I was thinking about these variables, if I remember correctly there are three variables so 1, 2 and 3 with the same name, so maybe we have to test it out properly before implementing but I will do so this week

**Comment by sjockers** [comment]
Related question / feature request: https://github.com/CorrelAid/pystatis/issues/104 ("Download Zenus data for other than Bundesland")

**Comment by pmayd** [comment]
I will implement this by end of the week!

**Comment by pmayd** [comment]
@bergnerjonas no actually the correct parameter is `regionalvariable` and `regionalkey`. If `classifyingvariable` can be used, too, its ok but I guess not the intended use case as regionalvariable only exists in Regio and Zensus database

**Comment by pmayd** [comment]
And I just noticed we already support that
