### ISSUE TITLE
Support Zensus 2022

### ISSUE THREAD

**Issue by bergnerjonas** [CorrelAid/pystatis#134]
The new zensus 2022 data release started: https://ergebnisse.zensus2022.de/datenbank/online
The new documentation can be found here: https://ergebnisse.zensus2022.de/datenbank/online/docs/ZENSUS-Webservices_Einfuehrung.pdf
Tasks:

- [x] Add new API url
- [x] Support authentification with API token
- [x] check for other changes in API wrt responsens, query parameters etc.

**Comment by bergnerjonas** [comment]
Current workaround: manually configure ~/.pystatis/config.ini:
[zensus]
base_url = https://ergebnisse.zensus2022.de/api/rest/2020/
username = <YOUR_USER>
password = <YOUR_PASSWORD>
doku = https://ergebnisse.zensus2022.de/datenbank/online/docs/ZENSUS-Webservices_Einfuehrung.pdf

=> Note that one needs to register a new account under https://ergebnisse.zensus2022.de/datenbank/online/

**Comment by pmayd** [comment]
There is a second way by deleting your config, easiest with pystatis.config.delete_config(). Next time you import pystatis it will create a new default config with the updated base url. After we publish a new release. Or manually deleting it, of course. If you have a . Env file with your credentials a single call to setup_credentials refills everything.
