### ISSUE TITLE
t.get_data()    ValueError: Missing column provided to 'parse_dates': 'Zeit'

### ISSUE THREAD

**Issue by goebbe** [CorrelAid/pystatis#160]
Ich habe heute erstmal pystatis ausprobiert und möchte es in der Zukunft einsetzen. 

Ich nutze pystatis v. 3.3
Umgebung: Jupyterlab, Python 3.12 (conda) auf LinuxMint22

Leider bin ich bereits beim Downloaden meiner Datentabelle gescheitert - und kann den Fehler leider selbst nicht beheben: 

Der Login scheint zu funktionieren: 
`pystatis.logincheck("genesis")`
'{"Status":"Sie wurden erfolgreich an- und abgemeldet! Bei mehr als 3 parallelen Requests wurden länger als 15 Minuten laufende Requests beendet.","Username":"xxx"}'

Auch Find funktioniert: 
```
from pystatis import Find
results = Find("Absatz von Bier", "genesis") # Initiates object that contains all variables, statistics, tables and cubes
results.tables.df # Results for tables
```
```
        Code            Content                                                                          Time
0 	73421-0001 	Absatz von Bier, betriebene Braustätten, Verbrauch von Bier: Deutschland, Jahre 	
1 	73421-0002 	Absatz von Bier: Deutschland, Monate 	
```

Das Feld "Time" ist in der Tabelle **nicht** gefüllt - vielleicht liegt hier das Problem? 
Die Information Jahre/ Monate scheint Teil der Beschreibung des "Content"

Nun zum Problem - folgender Code führt zu einer Fehlermeldung: 
```
import logging
logging.basicConfig(level=logging.INFO)
from pystatis import clear_cache
clear_cache()  # deletes the complete cache

from pystatis import Table
t = Table(name="73421-0002")
t.get_data()
```

Fehlermeldung: 
`ValueError: Missing column provided to 'parse_dates': 'Zeit'`

Außerdem habe ich es auch mit unterschiedlichen Zeitangaben versucht - leider mit der gleichen Fehlermeldung:
z.b.:  
`t.get_data(startyear = "2020",endyear = "2023")`

Hier noch die ausührliche Fehlermeldung (Traceback): 
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[40], line 11
      7 from pystatis import Table
      9 t = Table(name="73421-0002")
---> 11 t.get_data()
     13 t.get_data( prettify = True,
     14     area = '',
     15     startyear = "2020",
   (...)
     22     quality = False,
     23          )
     26 t.name

File [~/miniforge3/envs/sage/lib/python3.12/site-packages/pystatis/table.py:139](http://localhost:8888/lab/tree/sage/miniforge3/envs/sage/lib/python3.12/site-packages/pystatis/table.py#line=138), in Table.get_data(self, prettify, area, startyear, endyear, timeslices, regionalvariable, regionalkey, stand, language, quality)
    136 ags_codes = config.ZENSUS_AGS_CODES if db_name == "zensus" else config.REGIO_AND_GENESIS_AGS_CODES
    137 pos_of_ags_col = np.where(pd.Series(raw_data_lines[1].split(";")).isin(ags_codes))[0]
--> 139 self.data = pd.read_csv(
    140     data_buffer,
    141     sep=";",
    142     na_values=["...", ".", "-", "[/](http://localhost:8888/)", "x"],
    143     decimal="," if language == "de" else ".",
    144     dtype={raw_data_header.split(";")[pos + 2]: str for pos in pos_of_ags_col},
    145     parse_dates=[config.LANG_TO_COL_MAPPING[db_name][language]["time"]],
    146     date_format="%d.%m.%Y" if language == "de" else "%Y-%m-%d",
    147 )
    149 if prettify:
    150     self.data = self.prettify_table(
    151         data=self.data,
    152         db_name=db.identify_db_matches(self.name)[0],
    153         language=language,
    154     )

File [~/miniforge3/envs/sage/lib/python3.12/site-packages/pandas/io/parsers/readers.py:1026](http://localhost:8888/lab/tree/sage/miniforge3/envs/sage/lib/python3.12/site-packages/pandas/io/parsers/readers.py#line=1025), in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, date_format, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options, dtype_backend)
   1013 kwds_defaults = _refine_defaults_read(
   1014     dialect,
   1015     delimiter,
   (...)
   1022     dtype_backend=dtype_backend,
   1023 )
   1024 kwds.update(kwds_defaults)
-> 1026 return _read(filepath_or_buffer, kwds)

File [~/miniforge3/envs/sage/lib/python3.12/site-packages/pandas/io/parsers/readers.py:620](http://localhost:8888/lab/tree/sage/miniforge3/envs/sage/lib/python3.12/site-packages/pandas/io/parsers/readers.py#line=619), in _read(filepath_or_buffer, kwds)
    617 _validate_names(kwds.get("names", None))
    619 # Create the parser.
--> 620 parser = TextFileReader(filepath_or_buffer, **kwds)
    622 if chunksize or iterator:
    623     return parser

File [~/miniforge3/envs/sage/lib/python3.12/site-packages/pandas/io/parsers/readers.py:1620](http://localhost:8888/lab/tree/sage/miniforge3/envs/sage/lib/python3.12/site-packages/pandas/io/parsers/readers.py#line=1619), in TextFileReader.__init__(self, f, engine, **kwds)
   1617     self.options["has_index_names"] = kwds["has_index_names"]
   1619 self.handles: IOHandles | None = None
-> 1620 self._engine = self._make_engine(f, self.engine)

File [~/miniforge3/envs/sage/lib/python3.12/site-packages/pandas/io/parsers/readers.py:1898](http://localhost:8888/lab/tree/sage/miniforge3/envs/sage/lib/python3.12/site-packages/pandas/io/parsers/readers.py#line=1897), in TextFileReader._make_engine(self, f, engine)
   1895     raise ValueError(msg)
   1897 try:
-> 1898     return mapping[engine](f, **self.options)
   1899 except Exception:
   1900     if self.handles is not None:

File [~/miniforge3/envs/sage/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py:161](http://localhost:8888/lab/tree/sage/miniforge3/envs/sage/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py#line=160), in CParserWrapper.__init__(self, src, **kwds)
    155         self._validate_usecols_names(
    156             usecols,
    157             self.names,  # type: ignore[has-type]
    158         )
    160 # error: Cannot determine type of 'names'
--> 161 self._validate_parse_dates_presence(self.names)  # type: ignore[has-type]
    162 self._set_noconvert_columns()
    164 # error: Cannot determine type of 'names'

File [~/miniforge3/envs/sage/lib/python3.12/site-packages/pandas/io/parsers/base_parser.py:243](http://localhost:8888/lab/tree/sage/miniforge3/envs/sage/lib/python3.12/site-packages/pandas/io/parsers/base_parser.py#line=242), in ParserBase._validate_parse_dates_presence(self, columns)
    233 missing_cols = ", ".join(
    234     sorted(
    235         {
   (...)
    240     )
    241 )
    242 if missing_cols:
--> 243     raise ValueError(
    244         f"Missing column provided to 'parse_dates': '{missing_cols}'"
    245     )
    246 # Convert positions to actual column names
    247 return [
    248     col if (isinstance(col, str) or col in columns) else columns[col]
    249     for col in cols_needed
    250 ]

ValueError: Missing column provided to 'parse_dates': 'Zeit'
```

**Comment by pmayd** [comment]
Hallo @goebbe ! Freut uns sehr, einen neuen Nutzer der library zu haven!  Wie du richtig sagst, hat der Fehler nichts mit falschen Parametern zu tun, pystatis ist extra so konzipiert, dass man nichts falsch machen kann, eine Tabelle braucht lediglich die Evas Nummer bzw den Namen, um gedownloadet werden zu können, der Rest ist optional, um zB den Zeitraum der Abfrage anzupassen. Hier liegt also offenbar der Fall vor, dass die Zeit Dimension fehlt. Ich schaue mir das gerne an, vielleicht ist dies ein Sonderfall, den wir bisher nie hatten, oder die Tabelle ist defekt

**Comment by goebbe** [comment]
Vielen Dank für die schnelle Reaktion!
Es handelt sich um Daten der Gesis. 
Das Problem sollte sich anhand meines Beispiels leicht reproduzieren lassen. 

Über die rest API scheint der Download übrigens problemlos zu funktionieren, allerdings ist der Weg dann insgesamt relativ umständlich. 

Der folgende Weg führt bei mir zum Ziel. Außer dem Anfangsjahr musste ich auf diesem Weg auch keine weiteren Parameter spezifizieren: 
```
from urllib.request import urlretrieve
url = ( "https://www-genesis.destatis.de/genesisWS/rest/2020/data/tablefile?"
       "username="+KENNUNG+"&password="+PASSWORT+""
       "&name=73421-0002&startyear=1993&format=ffcsv&language=de"
      )
myzip = "genesis.zip"
urlretrieve(url, myzip)       
``` 

Daher mein Verdacht, dass es daran liegen könnte, dass die Variable "Time"  (Monat bzw. Jahr) hier nicht wie vorgesehen hinterlegt ist. Bei der Tabelle handelt es sich um monatliche Daten. 

Falls ich noch irgendetwas beitragen kann, bitte melden. :-)

**Comment by pmayd** [comment]
Hm das Beispiel ist interessant, hat Genesis bereits auf ZIP umgestellt? Dann liegt es daran. Bisher war das nur bei Zensus der Fall, Genesis und Regio waren noch auf dem alten Stand und haben Textdateien ausgeliefert. Wenn sie jetzt bereits auf zip umgestellt haben, dann kann pystatis nicht mehr funktionieren und wir müssen die library updaten. Das geht aber schnell.

**Comment by pmayd** [comment]
Genau, das wissen wir alles bereits, weil es bei Zensus schon länger so ist. Es wurde leider nur nicht öffentlich kommuniziert, wann die anderen Datenbanken umziehen. Wie gesagt haben wir bereits ein funktionierendes Parsing des neuen Formats für Zensus, aber noch nicht auf Genesis und Regionalstatistik angewendet. Die Änderungen sind Recht umfangreich, daher hoffe ich, dass wir unsere Lösung von Zensus einfach auf die anderen beiden anwenden können. Es sind nicht nur die Spaltennamen jetzt Englisch, sondern vor allem gibt es nur noch eine value Spalte, was leider nicht mehr tidy ist, daher wandeln wir den Datensatz von Long wieder in ein wide Format um. Müsste aber alles bereits in der Readme bzw in den Notebooks dokumentiert sein, was wir genau bei Zensus mit dem Format machen. Wie gesagt, ich schaue es mir an, wir brauchen keinen weiteren Code von dir, ich weiß ja bereits, woran es liegt :)****

**Comment by pmayd** [comment]
table is working again with newest version 0.4.0 which I will release in a few seconds ;)

**Comment by goebbe** [comment]
Vielen Dank!
