### ISSUE TITLE
Check if Zensus tables are identical with Genesis and RegioDB tables (format)

### ISSUE THREAD

**Issue by pmayd** [CorrelAid/pystatis#17]

**Comment by PiaSchroeder** [comment]
All seem to follow the same structure (i.e. they have the same columns):

0: Statistik_Code 
1: Statistik_Label
2: Zeit_Code
3: Zeit_Label
4: Zeit
5: 1_Merkmal_Code
6: 1_Merkmal_Label
7: 1_Auspraegung_Code
8: 1_Auspraegung_Label   
repeat 5-8 for further independent variables
columns with dependent variables are added in the end 

Only apparent difference: The Statistik_Code in GENESIS and RegioDB is an integer, in ZensusDB it’s a string. Probably makes sense to convert all into string.

**Comment by pmayd** [comment]
lets do the unit tests together once the PR is ready!
