### ISSUE TITLE
based on the list of all table numbers, derive a concept for matching a table number to a database

### ISSUE THREAD

**Issue by pmayd** [CorrelAid/pystatis#30]

**Comment by PiaSchroeder** [comment]
genesis_regex = "^\d{5}-\d{4}$"
regioDB_regex = "(^\d{5}-.{1,2}($|-.*$))|(^A.*$)"
zensusDB_regex = "^\d{4}[A-Z]-\d{4}$"

**Comment by PiaSchroeder** [comment]
[Notebook checking the regex matches](https://github.com/PiaSchroeder/pystatis_aux/blob/main/regex_tables.ipynb)

**Comment by pmayd** [comment]
Great approach! Would be nice to explain the logic behind the regex a little bit as regioDB is quite complex
