### ISSUE TITLE
make units accessible for users

### ISSUE THREAD

**Issue by pmayd** [CorrelAid/pystatis#33]
Each "Merkmal" must have a unit. Can we make the unit accessible for the user? What is the best way?

**Comment by PiaSchroeder** [comment]
In some tables (e.g. 1000A-1001), value columns contain alternating data entries with different units (in this case counts and percentages) that are resolved in another column (value_units). This column is currently removed by prettify_table, such that the value column becomes essentially unusable.
ToDo: Split the value column into two columns, each with a label indicating the unit.

**Comment by PhilippVerpoort** [comment]
Not sure if this is helpful, but `pint` ([GitHub](https://github.com/hgrecco/pint/), [ReadTheDocs](https://pint.readthedocs.io/)) is an excellent Python library for handling units. It also comes with an [integration into pandas](https://github.com/hgrecco/pint-pandas). Custom units can easily be defined as necessary.
