### ISSUE TITLE
Beispielanalysen mit (Geo-)Visualisierungen

### ISSUE THREAD

**Issue by pmayd** [CorrelAid/pystatis#34]

**Comment by pmayd** [comment]
@jkrause123 Siehe Demo von Simon zur Erstellung eine Karte

**Comment by pmayd** [comment]
Katapult Magazin

**Comment by sjockers** [comment]
Beispiel (JavaScript, ohne Nutzung der API):

https://observablehq.com/@sjockers/genesis-choroplethen

**Comment by jkrause123** [comment]
https://regionalatlas.statistikportal.de

**Comment by sjockers** [comment]
@jkrause123 Falls du Karten aus dem Regionalatlas nachbauen möchtest, kannst du auf die Daten über regionalstatistik.de zugreifen:

[EVAS-Nr. 99910: Regionalatlas Deutschland](https://www.regionalstatistik.de/genesis//online?operation=statistic&code=99910&levelindex=0&levelid=1699984340306#abreadcrumb)

**Comment by sjockers** [comment]
Jonas hat bereits dieses Notebook angelegt: https://github.com/CorrelAid/pystatis/blob/dev/nb/02_Geo_visualization_example.ipynb

Zu tun wäre:
1. Prüfen ob das Notebook so weiterhin funktioniert
2. In die Doku (Sphinx) integrieren (?)
3. Weitere Beispiele im gleichen Stil entwickeln

**Comment by pmayd** [comment]
Integration in die Doku fände ich super ,für alle notebooks
