### ISSUE TITLE
Implement regex matching

### ISSUE THREAD

**Issue by pmayd** [CorrelAid/pystatis#35]

**Comment by PiaSchroeder** [comment]
@pmayd I just started working on you comments and then only afterwards saw that you have already fixed some issues yourself. What's the current state, should I continue working on your comments (and if so, do I need to update my local branch first to integrate your changes?)

**Comment by pmayd** [comment]
Yep sorry I was just in the mood and thought it would be unfair to let you do the work on the Find class for example as you are not yet familiar with that code. 

So yes, you have to update your branch because I just continued working on your code so we have everything in place. Of course you can ignore my comments then or just look at what I did and give your two cents. I will try to add where I changed it already!
