### ISSUE TITLE
Add preprocessing for missing values

### ISSUE THREAD

**Issue by pmayd** [CorrelAid/pystatis#36]

**Comment by pmayd** [comment]
12211-0001

**Comment by jkrause123** [comment]
https://www.regionalstatistik.de/genesis/online?operation=ergebnistabelleQualitaet&language=de&levelindex=2&levelid=1702408035981#abreadcrumb

**Comment by jkrause123** [comment]
- abklären, ob wir die Zeichen richtig verstanden haben, mit Beispielen
- Qualitätsmerkmale mitbehandeln

**Comment by pmayd** [comment]
"Für den Tabellen-Download in den Formaten XLSX, CSV und FLAT kann die Ausgabe der Qualitätskennzeichen ( ), p, r, s und e durch Anklicken des Buttons Q unter Optionen aktiviert werden."

That means that these quality values are not visible by default in our FLAT CSV. But it is unclear how we can get the data from the API because there is no parameter. @jkrause123 could you ask in your email what parameter to choose to get this from the API or if this is not possible in ffcsv?

**Comment by MarcoHuebner** [comment]
Loose collection of ToDo's:
- AGS 0en ergänzen / 0en trimmen
- Datentypen und nicht nur Shape testen
- Enthält Merkmal auch Zahlen - oder nur str's?
- When parsing, try pd Datetime for "Zeit"

**Comment by pmayd** [comment]
- AGS data type issue is fixed. I search for AGS codes in the first row of the raw data string and if I find a match, I set this column to data type `str`
- datetime is now detected when reading in the data with `pd.read_csv` 

The other points are left for later
