### ISSUE TITLE
Unable to Retrieve Data from All Available Years using Table Function

### ISSUE THREAD

**Issue by Lacerdash** [CorrelAid/pystatis#5]
Hello,

I've been using the pystatis library and followed the example provided in the README. The only modification I made was to the table number to match my specific interest:
```
t = Table(name='32111-0004')  
t.get_data()  
df = t.data
```

Upon executing this code, I observed that the data returned was solely from the most recent year, 2021. To verify this, I checked the unique years in the dataframe:

`df.Zeit.unique()`

On manually accessing the statistical site, I noticed that users have the ability to specify which years they wish to download data from. Intriguingly, by default, the system is configured to fetch data from only the most recent year, as demonstrated [here with table 32111-0004](https://www-genesis.destatis.de/genesis//online?operation=table&code=32111-0004&bypass=true&levelindex=0&levelid=1693064881256#abreadcrumb).

I'm reaching out to inquire if there's a way to utilize the Table function, or any other functionality within the pystatis library, to download data spanning all available years.

Investigating further I noticed that this problem arises only in tables that has the default value for year set to the last year, such  as:

- [32111-0004](https://www-genesis.destatis.de/genesis//online?operation=table&code=32111-0004&bypass=true&levelindex=0&levelid=1693064881256#abreadcrumb)
- [32111-0011](https://www-genesis.destatis.de/genesis//online?operation=table&code=32111-0011&bypass=true&levelindex=0&levelid=1693064881256#abreadcrumb)
- [32136-0010](https://www-genesis.destatis.de/genesis//online?operation=table&code=32136-0010&bypass=true&levelindex=0&levelid=1693064881256#abreadcrumb)

Conversely, this wasn't an issue with tables where the default year value is set to encompass all years, as observed with:

- [32136-0001](https://www-genesis.destatis.de/genesis//online?operation=table&code=32136-0001&bypass=true&levelindex=0&levelid=1693064881256#abreadcrumb)

Thank you for your assistance!

**Comment by pmayd** [comment]
Will be fixed in the next version! We will add the available parameters to the `get_data` function so you can directly see that `startyear` etc is available!
