### ISSUE TITLE
Handle different languages

### ISSUE THREAD

**Issue by pmayd** [CorrelAid/pystatis#53]
The wrapper is downloading data in the German format (commas as decimals etc.) - so pandas doesn't recognize the columns as numbers. We would have to do it manually. Would it be possible to pass arguments similar to pd.read_csv(decimals=",", thousands=".") And have missing values as NaN instead of "-"? If I remember correctly, Michael said something about an English API endpoint that delivers data in a format that works better for pandas.

TODOs:
- compare Postman/raw data from API with our package when downloading the same table with language `de` and `en`
- implement a handling for these languages

**Comment by pmayd** [comment]
@bergnerjonas here what we discussed:
- it may be that Regionalstatistik does not have support for en so we can drop it there
- when there is no data, we should not go to additional API requests like /find or /catalogue to get the label for a given code
- we can try to parse the repeating code column names to get the right names, but we should investigate first how the switch to en is supported in different databases

**Comment by bergnerjonas** [comment]
Both GENESIS and Zensus currently support switching to 'en' and return proper translations. I have removed the support for Regionalstatsistik.

**Comment by pmayd** [comment]
Very good, I will review your PR this week!
