### ISSUE TITLE
Add Graphical Repo/ Code Base Overview

### ISSUE THREAD

**Issue by MarcoHuebner** [CorrelAid/pystatis#7]
Issue:
Currently, our codebase lacks a comprehensive graphical representation, making it challenging for (irregular) contributors and new developers to understand the overall structure. Introducing software engineering frameworks like class diagrams or data flow charts can significantly enhance the project's documentation and improve the onboarding experience.

Proposed Solution:
Create a graphical code base overview in whatever form suits best, which illustrates the relationships and dependencies between classes as well as paths users (have to) take to receive requested data. This diagram will serve as a high-level guide for developers, making it easier for them to navigate the codebase.

Implementation Steps:
- Research and select a suitable tool for generating such a diagram from code.
- Identify key classes and their relationships within the codebase.
- Generate the diagram.
- [Optional] Include the diagram in the project's documentation, e.g. Wiki and/ or Sphinx.
- [Optional] Update the README to guide contributors on how to interpret and use the class diagram.

**Comment by pmayd** [comment]
I looked for tools and the only one that I could find and which is free is [pycallgraph2](https://pypi.org/project/pycallgraph2/).

Sadly, it does not work with modules or libraries, but you have to specify a script that it analyzes, which means for it to work properly, we have to write a small script that executes the functions from pystatis in a meaningful way. To play around with it I just gave it the table.py module:

```bash
pycallgraph -i "pystatis.*" graphviz -- src/pystatis/table.py
```

and this is the result:


![Image](https://github.com/CorrelAid/pystatis/assets/9614291/b43eeaa9-0ec0-4365-9ebc-9459bf54d12c)

I guess this is not so bad and it can follow the function calls and show the dependencies. However, we need to write a proper execution script to see the dependencies clearly

**Comment by pmayd** [comment]
This is really cool, I just wrote this very small script:

```python
import pystatis

pystatis.set_db("genesis")

t = pystatis.Table("11111-0001")
t.get_data()
t.data
t.metadata
t.name
```

And the output is much better and more detailed related to Table class:


![Image](https://github.com/CorrelAid/pystatis/assets/9614291/4e437784-65d8-42c3-b077-b1347d643f07)

**Comment by MarcoHuebner** [comment]
I have no experience in that direction (yet), but the LLM of my trust pointed me to [Doxygen](https://www.doxygen.nl/) ("You can [configure](https://www.doxygen.nl/manual/starting.html#extract_all) doxygen to extract the code structure from undocumented source files. This is very useful to quickly find your way in large source distributions. Doxygen can also visualize the relations between the various elements by means of include dependency graphs, inheritance diagrams, and collaboration diagrams, which are all generated automatically.") and [PlantUML for VSCode](https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml). Do you have experience with one of the tools and perhaps already know that they do not work for our purpose?

**Comment by MarcoHuebner** [comment]
Quick update: I tried PlantUML and it didn't seem to be made for the purpose I thought, doxygen is not straight forward to set up for Windows (skipped for now), but `pyreverse -o png -p yourpackage .` (comes with pylint, requires graphviz) gave me some results (see below)

![Image](https://github.com/CorrelAid/pystatis/assets/57489799/c73e6189-2adc-46ba-9c45-9fe362749c44)
![Image](https://github.com/CorrelAid/pystatis/assets/57489799/6886b0e0-2416-4184-adb4-99dd45a0d8bb)

and [`code2flow`](https://github.com/scottrogowski/code2flow) worked even better (simply running `code2flow src/pystatis/*.py` - but it misses at least the custom errors from `exception.py`

![Image](https://github.com/CorrelAid/pystatis/assets/57489799/14777538-5a05-45cd-9e25-62fbca6fea4b)


Let me know what you think :)
