### ISSUE TITLE
Handle quality signs (quality on/off -> additional __q columns)

### ISSUE THREAD

**Issue by jkrause123** [CorrelAid/pystatis#83]
Für den Tabellen-Download in den Formaten XLSX, CSV und FLAT kann die Ausgabe der Qualitätskennzeichen ( ), p, r, s und e durch Anklicken des Buttons Q unter Optionen aktiviert werden.

– Schrägstrich und Klammer: Ab wann ein Wert so unsicher ist, dass er nicht mehr durch eine Klammer eingeschränkt, sondern durch einen Schrägstrich ersetzt werden muss, hängt von der Veröffentlichungspraxis in der jeweiligen Statistik ab.

In allen drei GENESIS-basierten Datenbanken können Sie mit dem API-Parameter quality=on die Ausgabe der Qualitätskennzeichen über die RESTful/JSON-Schnittstelle anfordern. Bitte beachten Sie auch hier die kompaktere API-Dokumentation der Zensusdatenbank:
https://ergebnisse2011.zensus2022.de/datenbank/misc/ZENSUS-Webservices_Einfuehrung.pdf
In Kürze werden sich in der Zensusdatenbank die Struktur und die Ausgabe des ffcsv-Format (zukünftig als zip-Archiv) ändern. Diese Änderungen werden dann sukzessive auf GENESIS-Online und in der Regionaldatenbank ausgerollt. Dezimaltrennzeichen werden dabei weiterhin sprachabhängig ausgegeben.

**Comment by MarcoHuebner** [comment]
Note: The Zensus documentation document (https://ergebnisse2011.zensus2022.de/datenbank/misc/ZENSUS-Webservices_Einfuehrung.pdf) is currently not reachable

**Comment by pmayd** [comment]
done in #117
