### ISSUE TITLE
Update project dependencies

### ISSUE THREAD

**Issue by pmayd** [CorrelAid/pystatis#9]
Make sure we use the latest package versions that are compatible with the project. 

Make sure everything still works and that the tests are green.

Should result in an updated `pyproject.toml` and `poetry.lock` file.

**Comment by MarcoHuebner** [comment]
TODO: update [dev-dependencies](https://python-poetry.org/docs/managing-dependencies/) in `pyproject.toml`

**Comment by MarcoHuebner** [comment]
I am closing this issue, since it has been addressed in #14 and both main and dev are green.
